<?php

namespace Doefom\CurrencyFieldtype\Utils;

use Statamic\Support\Arr;

class Currencies
{

    /**
     * Get the currency details by its ISO identifier ("EUR", "USD", etc.).
     * @param string $iso
     * @return array|null
     */
    public static function getCurrency(string $iso): array|null
    {
        return Arr::get(self::$currencyList, $iso);
    }

    /**
     * A list of currencies sorted by name with information about each currency.
     * @var array|array[]
     */
    public static array $currencyList = [
        "XUA" => ["name" => "ADB Unit of Account", "numeric_code" => "965"],
        "AFN" => ["name" => "Afghani", "numeric_code" => "971"],
        "DZD" => ["name" => "Algerian Dinar", "numeric_code" => "012"],
        "ARS" => ["name" => "Argentine Peso", "numeric_code" => "032"],
        "AMD" => ["name" => "Armenian Dram", "numeric_code" => "051"],
        "AWG" => ["name" => "Aruban Florin", "numeric_code" => "533"],
        "AUD" => ["name" => "Australian Dollar", "numeric_code" => "036"],
        "AZN" => ["name" => "Azerbaijan Manat", "numeric_code" => "944"],
        "BSD" => ["name" => "Bahamian Dollar", "numeric_code" => "044"],
        "BHD" => ["name" => "Bahraini Dinar", "numeric_code" => "048"],
        "THB" => ["name" => "Baht", "numeric_code" => "764"],
        "PAB" => ["name" => "Balboa", "numeric_code" => "590"],
        "BBD" => ["name" => "Barbados Dollar", "numeric_code" => "052"],
        "BYN" => ["name" => "Belarusian Ruble", "numeric_code" => "933"],
        "BZD" => ["name" => "Belize Dollar", "numeric_code" => "084"],
        "BMD" => ["name" => "Bermudian Dollar", "numeric_code" => "060"],
        "VES" => ["name" => "Bolívar Soberano", "numeric_code" => "928"],
        "VED" => ["name" => "Bolívar Soberano", "numeric_code" => "926"],
        "BOB" => ["name" => "Boliviano", "numeric_code" => "068"],
        "XBA" => ["name" => "Bond Markets Unit European Composite Unit (EURCO)", "numeric_code" => "955"],
        "XBB" => ["name" => "Bond Markets Unit European Monetary Unit (E.M.U.-6)", "numeric_code" => "956"],
        "XBD" => ["name" => "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", "numeric_code" => "958"],
        "XBC" => ["name" => "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", "numeric_code" => "957"],
        "BRL" => ["name" => "Brazilian Real", "numeric_code" => "986"],
        "BND" => ["name" => "Brunei Dollar", "numeric_code" => "096"],
        "BGN" => ["name" => "Bulgarian Lev", "numeric_code" => "975"],
        "BIF" => ["name" => "Burundi Franc", "numeric_code" => "108"],
        "CVE" => ["name" => "Cabo Verde Escudo", "numeric_code" => "132"],
        "CAD" => ["name" => "Canadian Dollar", "numeric_code" => "124"],
        "KYD" => ["name" => "Cayman Islands Dollar", "numeric_code" => "136"],
        "XOF" => ["name" => "CFA Franc BCEAO", "numeric_code" => "952"],
        "XAF" => ["name" => "CFA Franc BEAC", "numeric_code" => "950"],
        "XPF" => ["name" => "CFP Franc", "numeric_code" => "953"],
        "CLP" => ["name" => "Chilean Peso", "numeric_code" => "152"],
        "XTS" => ["name" => "Codes specifically reserved for testing purposes", "numeric_code" => "963"],
        "COP" => ["name" => "Colombian Peso", "numeric_code" => "170"],
        "KMF" => ["name" => "Comorian Franc ", "numeric_code" => "174"],
        "CDF" => ["name" => "Congolese Franc", "numeric_code" => "976"],
        "BAM" => ["name" => "Convertible Mark", "numeric_code" => "977"],
        "NIO" => ["name" => "Cordoba Oro", "numeric_code" => "558"],
        "CRC" => ["name" => "Costa Rican Colon", "numeric_code" => "188"],
        "CUP" => ["name" => "Cuban Peso", "numeric_code" => "192"],
        "CZK" => ["name" => "Czech Koruna", "numeric_code" => "203"],
        "GMD" => ["name" => "Dalasi", "numeric_code" => "270"],
        "DKK" => ["name" => "Danish Krone", "numeric_code" => "208"],
        "MKD" => ["name" => "Denar", "numeric_code" => "807"],
        "DJF" => ["name" => "Djibouti Franc", "numeric_code" => "262"],
        "STN" => ["name" => "Dobra", "numeric_code" => "930"],
        "DOP" => ["name" => "Dominican Peso", "numeric_code" => "214"],
        "VND" => ["name" => "Dong", "numeric_code" => "704"],
        "XCD" => ["name" => "East Caribbean Dollar", "numeric_code" => "951"],
        "EGP" => ["name" => "Egyptian Pound", "numeric_code" => "818"],
        "SVC" => ["name" => "El Salvador Colon", "numeric_code" => "222"],
        "ETB" => ["name" => "Ethiopian Birr", "numeric_code" => "230"],
        "EUR" => ["name" => "Euro", "numeric_code" => "978"],
        "FKP" => ["name" => "Falkland Islands Pound", "numeric_code" => "238"],
        "FJD" => ["name" => "Fiji Dollar", "numeric_code" => "242"],
        "HUF" => ["name" => "Forint", "numeric_code" => "348"],
        "GHS" => ["name" => "Ghana Cedi", "numeric_code" => "936"],
        "GIP" => ["name" => "Gibraltar Pound", "numeric_code" => "292"],
        "XAU" => ["name" => "Gold", "numeric_code" => "959"],
        "HTG" => ["name" => "Gourde", "numeric_code" => "332"],
        "PYG" => ["name" => "Guarani", "numeric_code" => "600"],
        "GNF" => ["name" => "Guinean Franc", "numeric_code" => "324"],
        "GYD" => ["name" => "Guyana Dollar", "numeric_code" => "328"],
        "HKD" => ["name" => "Hong Kong Dollar", "numeric_code" => "344"],
        "UAH" => ["name" => "Hryvnia", "numeric_code" => "980"],
        "ISK" => ["name" => "Iceland Krona", "numeric_code" => "352"],
        "INR" => ["name" => "Indian Rupee", "numeric_code" => "356"],
        "IRR" => ["name" => "Iranian Rial", "numeric_code" => "364"],
        "IQD" => ["name" => "Iraqi Dinar", "numeric_code" => "368"],
        "JMD" => ["name" => "Jamaican Dollar", "numeric_code" => "388"],
        "JOD" => ["name" => "Jordanian Dinar", "numeric_code" => "400"],
        "KES" => ["name" => "Kenyan Shilling", "numeric_code" => "404"],
        "PGK" => ["name" => "Kina", "numeric_code" => "598"],
        "KWD" => ["name" => "Kuwaiti Dinar", "numeric_code" => "414"],
        "AOA" => ["name" => "Kwanza", "numeric_code" => "973"],
        "MMK" => ["name" => "Kyat", "numeric_code" => "104"],
        "LAK" => ["name" => "Lao Kip", "numeric_code" => "418"],
        "GEL" => ["name" => "Lari", "numeric_code" => "981"],
        "LBP" => ["name" => "Lebanese Pound", "numeric_code" => "422"],
        "ALL" => ["name" => "Lek", "numeric_code" => "008"],
        "HNL" => ["name" => "Lempira", "numeric_code" => "340"],
        "SLE" => ["name" => "Leone", "numeric_code" => "925"],
        "SLL" => ["name" => "Leone", "numeric_code" => "694"],
        "LRD" => ["name" => "Liberian Dollar", "numeric_code" => "430"],
        "LYD" => ["name" => "Libyan Dinar", "numeric_code" => "434"],
        "SZL" => ["name" => "Lilangeni", "numeric_code" => "748"],
        "LSL" => ["name" => "Loti", "numeric_code" => "426"],
        "MGA" => ["name" => "Malagasy Ariary", "numeric_code" => "969"],
        "MWK" => ["name" => "Malawi Kwacha", "numeric_code" => "454"],
        "MYR" => ["name" => "Malaysian Ringgit", "numeric_code" => "458"],
        "MUR" => ["name" => "Mauritius Rupee", "numeric_code" => "480"],
        "MXN" => ["name" => "Mexican Peso", "numeric_code" => "484"],
        "MXV" => ["name" => "Mexican Unidad de Inversion (UDI)", "numeric_code" => "979"],
        "MDL" => ["name" => "Moldovan Leu", "numeric_code" => "498"],
        "MAD" => ["name" => "Moroccan Dirham", "numeric_code" => "504"],
        "MZN" => ["name" => "Mozambique Metical", "numeric_code" => "943"],
        "BOV" => ["name" => "Mvdol", "numeric_code" => "984"],
        "NGN" => ["name" => "Naira", "numeric_code" => "566"],
        "ERN" => ["name" => "Nakfa", "numeric_code" => "232"],
        "NAD" => ["name" => "Namibia Dollar", "numeric_code" => "516"],
        "NPR" => ["name" => "Nepalese Rupee", "numeric_code" => "524"],
        "ANG" => ["name" => "Netherlands Antillean Guilder", "numeric_code" => "532"],
        "ILS" => ["name" => "New Israeli Sheqel", "numeric_code" => "376"],
        "TWD" => ["name" => "New Taiwan Dollar", "numeric_code" => "901"],
        "NZD" => ["name" => "New Zealand Dollar", "numeric_code" => "554"],
        "BTN" => ["name" => "Ngultrum", "numeric_code" => "064"],
        "KPW" => ["name" => "North Korean Won", "numeric_code" => "408"],
        "NOK" => ["name" => "Norwegian Krone", "numeric_code" => "578"],
        "MRU" => ["name" => "Ouguiya", "numeric_code" => "929"],
        "TOP" => ["name" => "Pa’anga", "numeric_code" => "776"],
        "PKR" => ["name" => "Pakistan Rupee", "numeric_code" => "586"],
        "XPD" => ["name" => "Palladium", "numeric_code" => "964"],
        "MOP" => ["name" => "Pataca", "numeric_code" => "446"],
        "CUC" => ["name" => "Peso Convertible", "numeric_code" => "931"],
        "UYU" => ["name" => "Peso Uruguayo", "numeric_code" => "858"],
        "PHP" => ["name" => "Philippine Peso", "numeric_code" => "608"],
        "XPT" => ["name" => "Platinum", "numeric_code" => "962"],
        "GBP" => ["name" => "Pound Sterling", "numeric_code" => "826"],
        "BWP" => ["name" => "Pula", "numeric_code" => "072"],
        "QAR" => ["name" => "Qatari Rial", "numeric_code" => "634"],
        "GTQ" => ["name" => "Quetzal", "numeric_code" => "320"],
        "ZAR" => ["name" => "Rand", "numeric_code" => "710"],
        "OMR" => ["name" => "Rial Omani", "numeric_code" => "512"],
        "KHR" => ["name" => "Riel", "numeric_code" => "116"],
        "RON" => ["name" => "Romanian Leu", "numeric_code" => "946"],
        "MVR" => ["name" => "Rufiyaa", "numeric_code" => "462"],
        "IDR" => ["name" => "Rupiah", "numeric_code" => "360"],
        "RUB" => ["name" => "Russian Ruble", "numeric_code" => "643"],
        "RWF" => ["name" => "Rwanda Franc", "numeric_code" => "646"],
        "SHP" => ["name" => "Saint Helena Pound", "numeric_code" => "654"],
        "SAR" => ["name" => "Saudi Riyal", "numeric_code" => "682"],
        "XDR" => ["name" => "SDR (Special Drawing Right)", "numeric_code" => "960"],
        "RSD" => ["name" => "Serbian Dinar", "numeric_code" => "941"],
        "SCR" => ["name" => "Seychelles Rupee", "numeric_code" => "690"],
        "XAG" => ["name" => "Silver", "numeric_code" => "961"],
        "SGD" => ["name" => "Singapore Dollar", "numeric_code" => "702"],
        "PEN" => ["name" => "Sol", "numeric_code" => "604"],
        "SBD" => ["name" => "Solomon Islands Dollar", "numeric_code" => "090"],
        "KGS" => ["name" => "Som", "numeric_code" => "417"],
        "SOS" => ["name" => "Somali Shilling", "numeric_code" => "706"],
        "TJS" => ["name" => "Somoni", "numeric_code" => "972"],
        "SSP" => ["name" => "South Sudanese Pound", "numeric_code" => "728"],
        "LKR" => ["name" => "Sri Lanka Rupee", "numeric_code" => "144"],
        "XSU" => ["name" => "Sucre", "numeric_code" => "994"],
        "SDG" => ["name" => "Sudanese Pound", "numeric_code" => "938"],
        "SRD" => ["name" => "Surinam Dollar", "numeric_code" => "968"],
        "SEK" => ["name" => "Swedish Krona", "numeric_code" => "752"],
        "CHF" => ["name" => "Swiss Franc", "numeric_code" => "756"],
        "SYP" => ["name" => "Syrian Pound", "numeric_code" => "760"],
        "BDT" => ["name" => "Taka", "numeric_code" => "050"],
        "WST" => ["name" => "Tala", "numeric_code" => "882"],
        "TZS" => ["name" => "Tanzanian Shilling", "numeric_code" => "834"],
        "KZT" => ["name" => "Tenge", "numeric_code" => "398"],
        "XXX" => ["name" => "The codes assigned for transactions where no currency is involved", "numeric_code" => "999"],
        "TTD" => ["name" => "Trinidad and Tobago Dollar", "numeric_code" => "780"],
        "MNT" => ["name" => "Tugrik", "numeric_code" => "496"],
        "TND" => ["name" => "Tunisian Dinar", "numeric_code" => "788"],
        "TRY" => ["name" => "Turkish Lira", "numeric_code" => "949"],
        "TMT" => ["name" => "Turkmenistan New Manat", "numeric_code" => "934"],
        "AED" => ["name" => "UAE Dirham", "numeric_code" => "784"],
        "UGX" => ["name" => "Uganda Shilling", "numeric_code" => "800"],
        "CLF" => ["name" => "Unidad de Fomento", "numeric_code" => "990"],
        "COU" => ["name" => "Unidad de Valor Real", "numeric_code" => "970"],
        "UYW" => ["name" => "Unidad Previsional", "numeric_code" => "927"],
        "UYI" => ["name" => "Uruguay Peso en Unidades Indexadas (UI)", "numeric_code" => "940"],
        "USD" => ["name" => "US Dollar", "numeric_code" => "840"],
        "USN" => ["name" => "US Dollar (Next day)", "numeric_code" => "997"],
        "UZS" => ["name" => "Uzbekistan Sum", "numeric_code" => "860"],
        "VUV" => ["name" => "Vatu", "numeric_code" => "548"],
        "CHE" => ["name" => "WIR Euro", "numeric_code" => "947"],
        "CHW" => ["name" => "WIR Franc", "numeric_code" => "948"],
        "KRW" => ["name" => "Won", "numeric_code" => "410"],
        "YER" => ["name" => "Yemeni Rial", "numeric_code" => "886"],
        "JPY" => ["name" => "Yen", "numeric_code" => "392"],
        "CNY" => ["name" => "Yuan Renminbi", "numeric_code" => "156"],
        "ZMW" => ["name" => "Zambian Kwacha", "numeric_code" => "967"],
        "ZWL" => ["name" => "Zimbabwe Dollar", "numeric_code" => "932"],
        "PLN" => ["name" => "Zloty", "numeric_code" => "985"],
    ];

    public static array $top25 = [
        "USD" => ["name" => "US Dollar", "numeric_code" => "840"],
        "EUR" => ["name" => "Euro", "numeric_code" => "978"],
        "JPY" => ["name" => "Yen", "numeric_code" => "392"],
        "GBP" => ["name" => "Pound Sterling", "numeric_code" => "826"],
        "AUD" => ["name" => "Australian Dollar", "numeric_code" => "036"],
        "CAD" => ["name" => "Canadian Dollar", "numeric_code" => "124"],
        "CHF" => ["name" => "Swiss Franc", "numeric_code" => "756"],
        "CNY" => ["name" => "Yuan Renminbi", "numeric_code" => "156"],
        "SEK" => ["name" => "Swedish Krona", "numeric_code" => "752"],
        "MXN" => ["name" => "Mexican Peso", "numeric_code" => "484"],
        "NZD" => ["name" => "New Zealand Dollar", "numeric_code" => "554"],
        "SGD" => ["name" => "Singapore Dollar", "numeric_code" => "702"],
        "HKD" => ["name" => "Hong Kong Dollar", "numeric_code" => "344"],
        "NOK" => ["name" => "Norwegian Krone", "numeric_code" => "578"],
        "KRW" => ["name" => "Won", "numeric_code" => "410"],
        "TRY" => ["name" => "Turkish Lira", "numeric_code" => "949"],
        "INR" => ["name" => "Indian Rupee", "numeric_code" => "356"],
        "RUB" => ["name" => "Russian Ruble", "numeric_code" => "643"],
        "BRL" => ["name" => "Brazilian Real", "numeric_code" => "986"],
        "ZAR" => ["name" => "Rand", "numeric_code" => "710"],
        "DKK" => ["name" => "Danish Krone", "numeric_code" => "208"],
        "PLN" => ["name" => "Zloty", "numeric_code" => "985"],
        "TWD" => ["name" => "New Taiwan Dollar", "numeric_code" => "901"],
        "THB" => ["name" => "Baht", "numeric_code" => "764"],
        "MYR" => ["name" => "Malaysian Ringgit", "numeric_code" => "458"],
    ];

    /**
     * Get the symbol of a currency by its ISO identifier ("EUR", "USD", etc.).
     * @param string $iso
     * @return string|null
     */
    public static function getSymbol(string $iso): string|null
    {
        collect(\Doefom\CurrencyFieldtype\Utils\Currencies::$currencyList)->filter(fn($item, $key) => collect(\Doefom\CurrencyFieldtype\Utils\Currencies::$temp)->has($key));


        $currency = self::getCurrency($iso);
        return Arr::get($currency, 'symbol');
    }

}
